import os, sys, time, argparse, pickle, logging
from os.path import join as pjoin

import numpy as np
import open3d as o3d

from .mesh_postprocess_utils import init_label_colormap, project_to_triangle_mesh, write_ply_with_labels

def main():
    """
    This script processes the instance and semantic meshes generated by the pipeline with close-set semantics.
    Both meshes will be labeled with the corresponding ids and then mapped to the ground truth mesh.
    """

    task = 'NYU40'
    _, _, color_map, _ = init_label_colormap(task)
    
    result_folder = '/home/zilong/Disk_data/semantic_mapping_result'
    scene_num = 'scene0001_00'
    result_folder = pjoin(result_folder, scene_num, 'original_res_close-sem')
    
    gt_files_folder = '/media/zilong/Documents/MasterProject/scannet/scans/'
    pred_inst_mesh_f = pjoin(result_folder, 'instance_mesh_160.ply')
    pred_sem_mesh_f = pjoin(result_folder, 'semantic_mesh_160.ply')


    # ####################### Load the instance and semantic mesh #######################
    inst_mesh = o3d.t.io.read_triangle_mesh(pred_inst_mesh_f)
    vertex_colors = inst_mesh.vertex.colors.numpy()
    triangles = inst_mesh.triangle.indices.numpy()

    triangle_colors = vertex_colors[triangles[:, 0]]
    triangle_colors = (triangle_colors * 255.0).astype(np.uint8) # indexed by triangle-idx
    inst_colors = np.unique(triangle_colors, axis=0)


    sem_mesh = o3d.t.io.read_triangle_mesh(pred_sem_mesh_f)
    sem_vertex_colors = sem_mesh.vertex.colors.numpy()

    sem_triangle_colors = sem_vertex_colors[triangles[:, 0]]
    sem_triangle_colors = (sem_triangle_colors * 255.0).astype(np.uint8)
    sem_colors = np.unique(sem_triangle_colors, axis=0)


    # ####################### Create the semantic mesh #######################
    out_vertex_inst_id = np.zeros(vertex_colors.shape[0], dtype=np.uint16)
    out_vertex_labels = np.zeros(vertex_colors.shape[0], dtype=np.uint16)

    inst_iter = 1
    for inst_c in inst_colors:
        if np.array_equal(inst_c, [200, 200, 200]):
            continue

        # Get mask of vertices matching this color
        triangle_mask = np.all(triangle_colors == inst_c, axis=-1)
        inst_vertices = triangles[triangle_mask].flatten()
        out_vertex_inst_id[inst_vertices] = inst_iter
        inst_iter += 1

    for sem_c in sem_colors:
        if np.array_equal(sem_c, color_map['background']) or \
            np.array_equal(sem_c, [200, 200, 200]):
            continue

        sem_class_id = -1
        for i, v in enumerate(color_map.values()):
            if np.array_equal(sem_c, v):
                sem_class_id = i
                break
        if sem_class_id == -1:
            raise ValueError(f"Semantic id not found for color {sem_c}.")
        
        # Get mask of vertices matching this color
        triangle_mask = np.all(sem_triangle_colors == sem_c, axis=-1)
        sem_cls_vertices = triangles[triangle_mask].flatten()
        out_vertex_labels[sem_cls_vertices] = sem_class_id
    

    
    gt_sem_mesh_f = pjoin(
        gt_files_folder, scene_num, f'{scene_num}_vh_clean_2.labels.ply'
    )
    gt_sem_mesh = o3d.t.io.read_triangle_mesh(gt_sem_mesh_f)
    map_vertices = gt_sem_mesh.vertex.positions

    # Update the mesh to colors from close-set semantic, add the sem class to laebels
    inst_mesh.vertex.labels = o3d.core.Tensor(out_vertex_inst_id, 
        dtype=o3d.core.uint16, device=inst_mesh.device)
    
    map_inst_c, map_inst_id, map_sem_c, map_sem_label = project_to_triangle_mesh(
        inst_mesh, map_vertices, 
        color2=sem_vertex_colors, label2=out_vertex_labels,
        dist_thresh=0.05, device=inst_mesh.device
    )
    # write it via Plydata
    write_ply_with_labels(
        pjoin(result_folder, 'instance_mesh_map_gt.ply'), 
        map_vertices.numpy(), map_inst_c, map_inst_id, 
        gt_sem_mesh.triangle.indices.numpy()
    )

    write_ply_with_labels(
        pjoin(result_folder, 'semantic_mesh_map_gt.ply'), 
        map_vertices.numpy(), map_sem_c,  map_sem_label, 
        gt_sem_mesh.triangle.indices.numpy()
    )


if __name__=="__main__":
    # set files path
    # args = parse_args()
    # main(args)

    main()